from __future__ import annotations

from typing import Any, Protocol


class MarketDataClientProtocol(Protocol):
    def ensure_connected(self) -> None: ...

    def shutdown(self) -> None: ...

    def connection_status(self) -> dict[str, Any]: ...

    def last_error(self) -> dict[str, Any]: ...

    def terminal_info(self) -> dict[str, Any] | None: ...

    def account_info(self) -> dict[str, Any] | None: ...

    def symbols_get(self, group: str | None = None) -> list[dict[str, Any]]: ...

    def symbol_info(self, symbol: str) -> dict[str, Any] | None: ...

    def symbol_info_tick(self, symbol: str) -> dict[str, Any] | None: ...

    def symbol_select(self, symbol: str, enable: bool) -> bool: ...
